### ISSUE TITLE
drone ci : Pending 

### ISSUE THREAD

**Issue by pennpeng** [AlloVince/drone-ci-demo#4]
k8s：1.11.3
部署drone 1.0
在执行pipeline的时候一直是pending状态：
log：
```
{"commit":"941d5f9501ea5970d7f99ee44ba77aec0fa27582","error":"Post http:/api/v4/projects/root%2Fdrone-helloworld-demo/statuses/941d5f9501ea5970d7f99ee44ba77aec0fa27582?name=continuous-integration%2Fdrone%2Fpush\u0026state=pending\u0026target_url=http%3A%2F%2Fdrone.172.50.0.29.nip.io%2Froot%2Fdrone-helloworld-demo%2F2: dial tcp: lookup gitlab.172.50.0.29.nip.io on 10.68.0.2:53: read udp 172.20.2.21:57821-\u003e10.68.0.2:53: i/o timeout","event":"push","level":"warning","msg":"trigger: cannot create status","ref":"refs/heads/master","repo":"root/drone-helloworld-demo","time":"2019-04-03T10:51:39Z"}

```

**Comment by pennpeng** [comment]
是不是这个问题：
https://discourse.drone.io/t/0-8-build-permanently-pending/757
你在k8s上面怎么没有呢？

**Comment by AlloVince** [comment]
Log 里已经写了 i/o timeout， 应该是无法访问github造成的

**Comment by pennpeng** [comment]
不是网络问题，我解决了。
请问一下，如果一个仓库里面有不同的分支需要维护，使用sementic-release 怎么给不同分支做发布呢？

**Comment by pennpeng** [comment]
如果是发布 alpha版 beta版本 怎么用sementic-release来做发布呢？

**Comment by AlloVince** [comment]
具体如何解决的可以写出来方便其他人知道

> 请问一下，如果一个仓库里面有不同的分支需要维护，使用sementic-release 怎么给不同分支做发布呢？

一个仓库可以有多个分支，但是最终都会合并到master，master是唯一的发布分支，版本号一个项目肯定只有一套，不存在不同分支都能做发布的情况

> 如果是发布 alpha版 beta版本 怎么用sementic-release来做发布呢？

alpha, beta 这种并没有统一的定义，所以这和 sementic-release 要解决的问题无关。可以结合你们自己的情况限定分支或者tag做发布

**Comment by pennpeng** [comment]
我的意思是版本维护，比如2.0,3.0每个版本肯定会有小版本维护的，使用semantic release一直是在master上发布，那你怎么再去用他发布2. x
的内容呢？

**Comment by AlloVince** [comment]
在semantic-release配置一下分支，就可以基于非master分支做发布
https://semantic-release.gitbook.io/semantic-release/usage/configuration#branch
