### ISSUE TITLE
Could not resolve host

### ISSUE THREAD

**Issue by zhijiansd** [AlloVince/drone-ci-demo#6]
请问你是用的Minikube吗？我使用gogs+drone部署的，drone在clone时出现了错误: Could not resolve host。这是一个网络问题，使用docker-compose时我通过配置networks和aliases解决了这个问题，但是在kubernetes上，无法通过这种配置来指定。在drone的论坛上我也无法创建问题，想寻求你的帮助。

**Comment by AlloVince** [comment]
参考我的一篇关于minikube的文章 https://avnpc.com/pages/kubernetes-for-single-vps
检查一下CoreDNS服务手否正确运行

**Comment by zhijiansd** [comment]
> 参考我的一篇关于minikube文章的https://avnpc.com/pages/kubernetes-for-single-vps
> 检查一下CoreDNS服务手否正确运行

我使用的是多节点的kubernetes，我的其他pod的dns:
```bash
# cat /etc/resolv.conf 
nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local localdomain
options ndots:5
```
而drone-job的dns:
```bash
cat /etc/resolv.conf
--
2 | nameserver 10.96.0.10
3 | search adqjkblcj2pyjnbalex9v1f4a4nmpk4o.svc.cluster.local svc.cluster.local cluster.local localdomain
4 | options ndots:5
```
我很怀疑是不是dns文件不同导致的

**Comment by AlloVince** [comment]
dig 查看一下

**Comment by zhijiansd** [comment]
> dig 查看一下

我将gogs配置为nodeip:nodeport的地址，drone算是可以拉取构建代码了。但是又出现了另外的问题，plugins/docker插件无法拉取公网的镜像仓库，恼火
